[package]
name = "snow_report_mapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
serde = "1.0.140"
serde_derive = "1.0.140"
serde_json = "1.0.82"
